# Generated by Django 5.1 on 2024-09-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chatroomvisit_last_visited_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="last_msg",
            field=models.TextField(null=True),
        ),
    ]
