# Generated by Django 5.1 on 2024-09-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
